### ISSUE TITLE
Unexpected columns in "courts.csv" causing empty sqlite document

### ISSUE THREAD

**Issue by saraheyn** [mdlincoln/caselaw-to-sqlite#1]
Hi - first, thanks so much for this script! It has worked on 90% of my case downloads. But there are 5 states that cause it to crash, and my troubleshooting has come to no avail. 

I have researcher access, so I have downloaded all cases from all states as jsonl.xz documents. There are 5 states that don't work - coming up with the following error:

extracting cases...done
extracting citations...done
extracting courts...done
extracting jurisdictions...done
extracting opinions...done
extracting parties...done
extracting attorneys...done
extracting judgesdone
Loading into caselaw.sqlite
PRAGMA foreign_keys = ON;
BEGIN;
CREATE TABLE IF NOT EXISTS courts (
  id INTEGER PRIMARY KEY NOT NULL,
  `name` TEXT NOT NULL,
  name_abbreviation TEXT NOT NULL,
  jurisdiction_url TEXT,
  slug TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS jurisdictions (
  id INTEGER PRIMARY KEY NOT NULL,
  slug TEXT NOT NULL,
  `name` TEXT NOT NULL,
  name_long TEXT NOT NULL,
  whitelisted TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS cases (
  id INTEGER PRIMARY KEY NOT NULL,
  `name` TEXT NOT NULL,
  name_abbreviation TEXT NOT NULL,
  decision_date TEXT NOT NULL,
  docket_number TEXT NOT NULL,
  first_page INTEGER NOT NULL,
  last_page INTEGER NOT NULL,
  volume_number INTEGER NOT NULL,
  reporter TEXT NOT NULL,
  court_id INTEGER NOT NULL,
  jurisdiction_id INTEGER NOT NULL,
  `status` TEXT NOT NULL,
  head_matter TEXT NOT NULL,
  FOREIGN KEY(court_id) REFERENCES courts(id),
  FOREIGN KEY(jurisdiction_id) REFERENCES jurisdictions(id)
);
CREATE TABLE IF NOT EXISTS opinions (
  id INTEGER NOT NULL,
  `type` TEXT NOT NULL,
  `text` TEXT NOT NULL,
  author TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES cases(id)
);
CREATE TABLE IF NOT EXISTS parties (
  id INTEGER NOT NULL,
  party TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES cases(id)
);
CREATE TABLE IF NOT EXISTS attorneys (
  id INTEGER NOT NULL,
  attorney TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES cases(id)
);
CREATE TABLE IF NOT EXISTS judges (
  id INTEGER NOT NULL,
  judge TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES cases(id)
);
.mode csv
.import courts.csv courts
courts.csv:20: unescaped " character
courts.csv:19: expected 5 columns but found 6 - extras ignored
courts.csv:27: expected 5 columns but found 3 - filling the rest with NULL
courts.csv:27: INSERT failed: datatype mismatch

The script then ends and the sqlite output file is empty. For the life of me I cannot figure out what the problem is, I just bulk downloaded all of the data. 

If it helps, the states are: Connecticut, Delaware, Texas, New York, Louisiana, and California.

Thanks so much!

**Comment by mdlincoln** [comment]
Hi @saraheyn, thanks for trying this out! The crux of this does seem to be the `courts.csv`.

However, given that it's complaining about an unescaped `"` character, I suspect perhaps there is some badly formed text in the original JSON, which then somehow made it to the CSV file that is supposed to go to sqlite. This is somewhat surprising, as if there was oddly formatted json I would have assumed that jq would have complained first before the data made it all the way to sqlite.

I'm following up with the Case Law / LexisNexis folks, since I hadn't yet received bulk access to the rest of the states yet... when I do I can take a look at the states you mentioned to see what might be going wrong.

**Comment by saraheyn** [comment]
Wonderful! Thanks so much @mdlincoln, and keep me updated! Let me know if you need any more info!

**Comment by mdlincoln** [comment]
Hey @saraheyn I finally got around to getting my bulk access... will look into it now.

**Comment by mdlincoln** [comment]
The issue is that there are line breaks in some of the names of the `courts`. When jq writes these out as CSV, the line breaks are emitted as well, and when I call `sort` on the file, it ends up putting those line fragments up at the top of the file.

The solution is either to have `jq` do the sorting, or to not do any deduplication at the CSV level, and instead ask sqlite to do the deduplication. I'll see which one looks faster and then push a fix.
